INSERT INTO kategorie (Nazwa) VALUES
('Malarstwo olejne'),
('Malarstwo akrylowe'),
('Malarstwo akwarelowe'),
('Malarstwo temperowe'),
('Malarstwo pastelowe'),
('Malarstwo guashe'),
('Malarstwo olejne na płótnie'),
('Malarstwo olejne na desce'),
('Malarstwo akrylowe na płótnie'),
('Malarstwo akrylowe na papierze'),
('Malarstwo cyfrowe'),
('Malarstwo na jedwabiu'),
('Malarstwo na porcelanie'),
('Malarstwo na szkle'),
('Malarstwo na tkaninie'),
('Malarstwo na drewnie'),
('Malarstwo na metalu'),
('Malarstwo na kamieniu'),
('Malarstwo na glinie'),
('Malarstwo na skórze'),
('Malarstwo na betonie'),
('Malarstwo na płótnie z wykorzystaniem techniki podziurawiania'),
('Malarstwo na płótnie z wykorzystaniem techniki fresku'),
('Malarstwo na płótnie z wykorzystaniem techniki batik'),
('Malarstwo na płótnie z wykorzystaniem techniki wyklejania'),
('Malarstwo na płótnie z wykorzystaniem techniki kolażu'),
('Malarstwo na płótnie z wykorzystaniem techniki transferu'),
('Malarstwo na płótnie z wykorzystaniem techniki szablonu'),
('Malarstwo na płótnie z wykorzystaniem techniki decoupage'),
('Malarstwo na płótnie z wykorzystaniem techniki monotypii'),
('Malarstwo na płótnie z wykorzystaniem techniki akwaforty'),
('Malarstwo na płótnie z wykorzystaniem techniki linorytu'),
('Malarstwo na płótnie z wykorzystaniem techniki drzeworytu'),
('Malarstwo na płótnie z wykorzystaniem techniki sitodruku'),
('Malarstwo na płótnie z wykorzystaniem techniki offsetu'),
('Malarstwo na płótnie z wykorzystaniem techniki litografii'),
('Malarstwo na płótnie z wykorzystaniem techniki gwaszu'),
('Malarstwo na płótnie z wykorzystaniem techniki inkluzyjnej'),
('Malarstwo na płótnie z wykorzystaniem techniki mieszanej'),
('Rysunek tuszem'),
('Rysunek węglem'),
('Rysunek markerem'),
('Rysunek kredkami'),
('Rzeźba w drewnie'),
('Rzeźba w kamieniu'),
('Rzeźba w metalu'),
('Rzeźba w glinie'),
('Rzeźba w brązie'),
('Rzeźba w marmurze'),
('Rzeźba w granicie'),
('Rzeźba w alabastrze'),
('Witraż'),
('Mozaika szklana'),
('Mozaika ceramika'),
('Mozaika kamieni rzecznych'),
('Ceramika rzeźbiarska'),
('Ceramika garncarska'),
('Ceramika artystyczna'),
('Ceramika użytkowa'),
('Szkło dmuchane'),
('Szkło rzeźbiarskie'),
('Szkło fusing'),
('Tkanina haftowana'),
('Tkanina batikowana'),
('Tkanina malowana'),
('Tkanina applikowana'),
('Fotografia czarno-biała'),
('Fotografia kolorowa'),
('Meblarstwo'),
('Jubilerstwo'),
('Ludwisarstwo'),
('Sztuka interaktywna');

