INSERT INTO kontrahenci (Typ, Imie, Nazwisko, Ulica, NrBudynku, NrLokalu, KodPoczt, Miejscowosc, NrZezwolenia) VALUES
('Klient', 'Jan', 'Kowalski', 'Aleja Kwiatowa', '12', NULL, '12-345', 'Warszawa'),
('Klient', 'Anna', 'Nowak', 'ul. Słoneczna', '5', '3A', '45-678', 'Kraków'),
('Klient', 'Piotr', 'Dąbrowski', 'ul. Leszczynowa', '7', NULL, '90-123', 'Łódź'),
('Klient', 'Małgorzata', 'Wójcik', 'ul. Polna', '3', '9', '34-567', 'Gdańsk'),
('Klient', 'Krzysztof', 'Lis', 'ul. Ogrodowa', '22', NULL, '01-234', 'Wrocław'),
('Klient', 'Agnieszka', 'Zielińska', 'ul. Górna', '18', NULL, '67-890', 'Poznań'),
('Klient', 'Marek', 'Wolski', 'ul. Leśna', '30', NULL, '56-789', 'Katowice'),
('Klient', 'Ewa', 'Kaczmarek', 'Plac Ratuszowy', '8', NULL, '89-012', 'Szczecin'),
('Klient', 'Andrzej', 'Kubiak', 'ul. Kwiatowa', '1', '2B', '23-456', 'Bydgoszcz'),
('Klient', 'Magdalena', 'Mazurek', 'Aleja Północna', '42', NULL, '45-678', 'Lublin'),
('Klient', 'Mariusz', 'Lewandowski', 'ul. Długa', '15', NULL, '67-890', 'Gdynia'),
('Klient', 'Beata', 'Kowalczyk', 'ul. Morska', '9', NULL, '12-345', 'Kraków'),
('Klient', 'Tomasz', 'Adamczyk', 'ul. Zielona', '20', NULL, '90-123', 'Wrocław'),
('Klient', 'Joanna', 'Sikora', 'ul. Słoneczna', '7', '4C', '34-567', 'Warszawa'),
('Klient', 'Robert', 'Kowal', 'ul. Wiosenna', '2', NULL, '01-234', 'Łódź'),
('Klient', 'Katarzyna', 'Gajewska', 'ul. Cicha', '11', NULL, '45-678', 'Poznań'),
('Klient', 'Radosław', 'Czajka', 'ul. Nadmorska', '3', '1A', '67-890', 'Kraków'),
('Klient', 'Monika', 'Kaczor', 'ul. Błyskawiczna', '10', NULL, '12-345', 'Szczecin'),
('Klient', 'Łukasz', 'Kowal', 'ul. Brzozowa', '6', NULL, '23-456', 'Katowice'),
('Klient', 'Karolina', 'Szymańska', 'ul. Parkowa', '28', NULL, '45-678', 'Gdańsk'),
('Klient', 'Artur', 'Dudek', 'ul. Letnia', '14', NULL, '56-789', 'Lublin'),
('Klient', 'Natalia', 'Czajkowska', 'ul. Nadmorska', '33', NULL, '67-890', 'Kraków'),
('Klient', 'Paweł', 'Kaczmarek', 'ul. Krótka', '4', NULL, '01-234', 'Gdynia'),
('Klient', 'Justyna', 'Nowak', 'ul. Główna', '17', NULL, '23-456', 'Wrocław'),
('Klient', 'Dariusz', 'Lis', 'ul. Biała', '9', NULL, '67-890', 'Bydgoszcz'),
('Klient', 'Alicja', 'Wojcik', 'ul. Ogrodowa', '5', '2B', '12-345', 'Warszawa'),
('Klient', 'Kamil', 'Zawisza', 'ul. Prosta', '16', NULL, '45-678', 'Lublin'),
('Klient', 'Paulina', 'Rutkowska', 'ul. Jasna', '27', NULL, '90-123', 'Poznań'),
('Klient', 'Marcin', 'Wojciechowski', 'ul. Urocza', '8', '3A', '34-567', 'Kraków'),
('Klient', 'Marta', 'Sobolewska', 'ul. Wiejska', '13', NULL, '45-678', 'Warszawa'),
('Klient', 'Damian', 'Szewczyk', 'ul. Górna', '22', NULL, '01-234', 'Wrocław'),
('Klient', 'Kinga', 'Mazurek', 'ul. Sienkiewicza', '6', NULL, '56-789', 'Szczecin'),
('Klient', 'Bartosz', 'Pawłowski', 'ul. Polna', '12', NULL, '67-890', 'Gdańsk'),
('Klient', 'Nina', 'Mazur', 'ul. Podgórna', '7', '4C', '45-678', 'Katowice'),
('Klient', 'Szymon', 'Kowalski', 'ul. Dolna', '10', NULL, '23-456', 'Kraków'),
('Klient', 'Wiktoria', 'Kowalczyk', 'ul. Dolna', '12', '1A', '12-345', 'Poznań'),
('Klient', 'Kacper', 'Kaczmarek', 'ul. Spacerowa', '30', NULL, '90-123', 'Gdynia'),
('Klient', 'Oliwia', 'Kowal', 'ul. Poziomkowa', '3', NULL, '34-567', 'Wrocław'),
('Klient', 'Daniel', 'Zieliński', 'ul. Łąkowa', '18', NULL, '67-890', 'Warszawa'),
('Klient', 'Zofia', 'Kaczor', 'ul. Parkowa', '16', '2B', '01-234', 'Poznań'),
('Klient', 'Filip', 'Wojciech', 'ul. Leśna', '9', NULL, '12-345', 'Kraków'),
('Klient', 'Emilia', 'Mazurek', 'ul. Wiejska', '28', NULL, '45-678', 'Gdańsk'),
('Klient', 'Gabriel', 'Matuszak', 'ul. Błyskawiczna', '5', NULL, '56-789', 'Szczecin'),
('Klient', 'Hanna', 'Olszewska', 'ul. Sienkiewicza', '17', NULL, '67-890', 'Warszawa'),
('Klient', 'Leon', 'Szewczyk', 'ul. Prosta', '11', NULL, '23-456', 'Kraków'),
('Klient', 'Mikołaj', 'Pawłowska', 'ul. Główna', '20', '4C', '45-678', 'Poznań'),
('Klient', 'Julia', 'Rutkowski', 'ul. Urocza', '14', '3A', '90-123', 'Katowice'),
('Klient', 'Oskar', 'Kaczor', 'ul. Podgórna', '6', NULL, '67-890', 'Gdynia');

INSERT INTO kontrahenci (Typ, Imie, Nazwisko, Ulica, NrBudynku, NrLokalu, KodPoczt, Miejscowosc, Biografia,NrZezwolenia) VALUES
('Ubezpieczyciel','Magdalena', 'Kaczmarek', 'Katowicka', '31', '5', '40-501', 'Katowice', NULL,'XD3240130'),
('Ubezpieczyciel','Krzysztof', 'Szymański', 'Szczecińska', '20', '8', '70-200', 'Szczecin', NULL,'AA8888DDI'),
('Ubezpieczyciel','Barbara', 'Wojciechowska', 'Lubelska', '8', '14', '20-100', 'Lublin', NULL,'EI088E912'),
('Ubezpieczyciel','Andrzej', 'Dąbrowski', 'Białostocka', '22', NULL, '15-050', 'Białystok', NULL,'PP9983312'),
('Ubezpieczyciel','Karolina', 'Pawlak', 'Rzeszowska', '6', '1C', '35-300', 'Rzeszów', NULL,'I92375HU3');



INSERT INTO kontrahenci (Typ, Imie, Nazwisko, Ulica, NrBudynku, NrLokalu, KodPoczt, Miejscowosc, Biografia) VALUES
('Artysta','Jan', 'Kowalski', 'Aleja Słoneczna', '1', NULL, '01-100', 'Warszawa', 'Jan Kowalski jest uznanym malarzem pejzażystą. Studiował sztuki piękne na Uniwersytecie Sztuk Pięknych w Warszawie.'),
('Artysta','Anna', 'Nowak', 'ul. Malarzy', '15', '2B', '30-200', 'Kraków', 'Anna Nowak to utalentowana rzeźbiarka, która swoją inspirację czerpie z natury i abstrakcji.'),
('Artysta','Piotr', 'Wójcik', 'Plac Nowy', '7', '3A', '50-010', 'Wrocław', 'Piotr Wójcik jest znanym artystą multimedialnym, eksperymentuje z różnymi formami i technikami.'),
('Artysta','Monika', 'Kwiatkowska', 'Morska', '21', '1A', '70-007', 'Szczecin', 'Monika Kwiatkowska jest artystką grafikiem.'),
('Artysta','Paweł', 'Nowakowski', 'Bieszczadzka', '1', NULL, '35-008', 'Rzeszów', 'Paweł Nowakowski maluje w technice olejnej.'),
('Artysta','Katarzyna', 'Adamczyk', 'Świderska', '13', '2C', '10-009', 'Olsztyn', 'Katarzyna Adamczyk jest fotografem krajobrazu.'),
('Artysta','Jakub', 'Wojciech', 'Kopernika', '9', NULL, '90-010', 'Poznań', 'Jakub Wojciech tworzy w dziedzinie sztuki video-artu.'),
('Artysta','Tomasz', 'Szymański', 'ul. Kamienna', '5', '12', '40-500', 'Katowice', 'Tomasz Szymański to artysta, którego prace odzwierciedlają miasto i przemysł.'),
('Artysta','Maria', 'Lis', 'ul. Polna', '8', NULL, '70-100', 'Szczecin', 'Maria Lis to uznaną artystka grafik i ilustratorek, jej prace często są używane w książkach i magazynach.'),
('Artysta','Krzysztof', 'Pawlak', 'Aleja Artystów', '12', '5', '90-001', 'Łódź', 'Krzysztof Pawlak jest artystą fotografikiem, specjalizuje się w fotografii krajobrazowej.'),
('Artysta','Barbara', 'Wojciechowska', 'Plac Kwiatowy', '3', NULL, '15-050', 'Białystok', 'Barbara Wojciechowska to artystka wizualna, jej prace często poruszają tematykę społeczną i polityczną.'),
('Artysta','Andrzej', 'Wieczorek', 'Aleja Awangardy', '6', '1C', '35-300', 'Rzeszów', 'Andrzej Wieczorek to artysta multimedialny i performer, który swoją twórczość prezentuje na różnych festiwalach.'),
('Artysta','Magdalena', 'Dąbrowska', 'ul. Niezapomniana', '25', NULL, '10-100', 'Olsztyn', 'Magdalena Dąbrowska jest rzeźbiarką specjalizującą się w tworzeniu prac monumentalnych.'),
('Artysta','Wojciech', 'Kowalczyk', 'Plac Sadzawki', '30', '4B', '80-300', 'Gdańsk', 'Wojciech Kowalczyk to malarz pejzażysta, który odwiedził wiele miejsc na całym świecie i czerpie inspirację z podróży.'),
('Artysta','Alicja', 'Kaczmarek', 'ul. Marynistyczna', '9', NULL, '20-500', 'Lublin', 'Alicja Kaczmarek to artystka konceptualna, która często eksploruje abstrakcję i minimalizm.'),
('Artysta','Artur', 'Nowak', 'Aleja Słoneczna', '14', '7A', '00-500', 'Warszawa', 'Artur Nowak jest artystą wizualnym, specjalizuje się w fotomontażach i kolażach.'),
('Artysta','Natalia', 'Kwiatkowska', 'ul. Stała', '18', NULL, '61-200', 'Poznań', 'Natalia Kwiatkowska to artystka malarzka, jej prace często eksplorują kształty i kolory.'),
('Artysta','Marcin', 'Szymański', 'ul. Wroga', '21', '11', '40-300', 'Katowice', 'Marcin Szymański to fotografik, który specjalizuje się w fotografii portretowej.'),
('Artysta','Monika', 'Zając', 'Aleja Artystów', '27', NULL, '70-200', 'Szczecin', 'Monika Zając to artystka wizualna i performance, jej prace często angażują widza emocjonalnie.'),
('Artysta','Tadeusz', 'Kowalski', 'Plac Sztalugi', '11', '8', '15-100', 'Białystok', 'Tadeusz Kowalski to malarz abstrakcyjny, który eksperymentuje z różnymi materiałami.'),
('Artysta','Katarzyna', 'Lis', 'ul. Malarzy', '4', '3C', '50-300', 'Wrocław', 'Katarzyna Lis to artystka rzeźbiarka, specjalizująca się w pracach z drewna i kamienia.'),
('Artysta','Marek', 'Wójcik', 'Aleja Drzewna', '19', NULL, '30-300', 'Kraków', 'Marek Wójcik to artysta multimedialny, który często łączy różne media w swoich pracach.'),
('Artysta','Agnieszka', 'Nowak', 'ul. Klonowa', '13', NULL, '60-100', 'Poznań', 'Agnieszka Nowak to artystka konceptualna, jej prace często wywołują refleksje na temat zmian klimatycznych.'),
('Artysta','Bartosz', 'Kaczmarek', 'ul. Lwia', '23', '9', '40-001', 'Katowice', 'Bartosz Kaczmarek to artysta wizualny, który eksploruje tematykę miejską i architektoniczną.'),
('Artysta','Aleksandra', 'Wieczorek', 'Plac Sztuki', '16', '2A', '20-200', 'Lublin', 'Aleksandra Wieczorek to artystka grafik, która specjalizuje się w ilustracjach dla dzieci.'),
('Artysta','Mariusz', 'Dąbrowski', 'ul. Liliowa', '7', NULL, '15-300', 'Białystok', 'Mariusz Dąbrowski to artysta fotografik, który uwiecznia piękno przyrody.'),
('Artysta','Agnieszka', 'Wojciechowska', 'Aleja Koperkowa', '2', NULL, '90-200', 'Łódź', 'Agnieszka Wojciechowska to artystka multimedialna, która eksperymentuje z dźwiękiem i obrazem.'),
('Artysta','Rafał', 'Pawlak', 'ul. Manii', '22', '5', '50-050', 'Wrocław', 'Rafał Pawlak to malarz pejzażysta, który inspirację czerpie z podróży po górach i lasach.'),
('Artysta','Joanna', 'Wieczorek', 'ul. Warunkowa', '29', '7B', '60-050', 'Poznań', 'Joanna Wieczorek to artystka rzeźbiarka, która tworzy prace z metalu i stali.'),
('Artysta','Kamil', 'Kaczmarek', 'Plac I Wojny', '20', NULL, '20-300', 'Lublin', 'Kamil Kaczmarek to artysta konceptualny, który często eksploruje tematykę tożsamości i tożsamości płciowej.'),
('Artysta','Olga', 'Nowak', 'ul. Karmelowa', '12', '4A', '70-050', 'Szczecin', 'Olga Nowak to artystka wizualna, która specjalizuje się w fotomontażach.'),
('Artysta','Radosław', 'Kowalski', 'Aleja Wdowia', '10', NULL, '40-300', 'Katowice', 'Radosław Kowalski to fotografik, który uwiecznia życie uliczne i miejskie krajobrazy.'),
('Artysta','Dominika', 'Lis', 'ul. Morska', '5', NULL, '10-300', 'Olsztyn', 'Dominika Lis to artystka grafik, która specjalizuje się w ilustracjach dla dzieci.'),
('Artysta','Łukasz', 'Wójcik', 'ul. Sokola', '26', '11', '80-050', 'Gdańsk', 'Łukasz Wójcik to artysta multimedialny, który tworzy prace interaktywne i eksperymentalne.'),
('Artysta','Kamila', 'Nowak', 'Plac Sezamkowy', '28', NULL, '15-200', 'Białystok', 'Kamila Nowak to artystka konceptualna, która często łączy różne media w swoich pracach.'),
('Artysta','Marek', 'Kowalczyk', 'Aleja Amsterdamska', '14', '8A', '40-200', 'Katowice', 'Marek Kowalczyk to malarz abstrakcyjny, który eksperymentuje z formą i kolorem.'),
('Artysta','Dorota', 'Kaczmarek', 'ul. Cebulowa', '19', NULL, '10-050', 'Łódź', 'Dorota Kaczmarek to artystka multimedialna, która eksperymentuje z dźwiękiem i światłem.'),
('Artysta','Krzysztof', 'Szymański', 'ul. Jelenia', '24', '3D', '50-100', 'Wrocław', 'Krzysztof Szymański to rzeźbiarz, który tworzy prace w technice metaloplastyki.'),
('Artysta','Magdalena', 'Kowalska', 'Plac Sosnowy', '16', NULL, '20-050', 'Lublin', 'Magdalena Kowalska to artystka wizualna, specjalizuje się w fotomontażach.'),
('Artysta','Paweł', 'Nowak', 'Aleja Sztuki', '7', NULL, '70-300', 'Szczecin', 'Paweł Nowak to fotografik, który uwiecznia piękno przyrody i krajobrazów miejskich.'),
('Artysta','Inesz', 'Lis', 'ul. Artystyczna', '11', '5', '10-100', 'Olsztyn', 'Inesz Lis to artystka konceptualna, której prace często angażują widza emocjonalnie.'),
('Artysta','Weronika', 'Kaczmarek', 'ul. Murarzy', '13', '4C', '80-100', 'Gdańsk', 'Weronika Kaczmarek to artystka wizualna, która eksploruje tematykę miejską i architektoniczną.'),
('Artysta','Marek', 'Wójcik', 'Plac Sztuki', '25', NULL, '15-300', 'Białystok', 'Marek Wójcik to artysta multimedialny, specjalizujący się w tworzeniu instalacji artystycznych.'),
('Artysta','Anna', 'Kowalska', 'Aleja Polski', '9', '6A', '40-100', 'Katowice', 'Anna Kowalska to malarz pejzażysta, jej prace często odzwierciedlają piękno natury.'),
('Artysta','Jan', 'Nowak', 'ul. Muzy', '17', NULL, '20-300', 'Lublin', 'Jan Nowak to rzeźbiarz, który tworzy prace w technice metaloplastyki.'),
('Artysta','Ewa', 'Wiśniewska', 'ul. Arrasowa', '29', '11', '70-001', 'Łódź', 'Ewa Wiśniewska to artystka konceptualna, która często eksploruje tematykę społeczną i polityczną.'),
('Artysta','Piotr', 'Lis', 'Plac Wolności', '23', NULL, '50-200', 'Wrocław', 'Piotr Lis to artysta wizualny, specjalizuje się w tworzeniu prac interaktywnych i eksperymentalnych.'),
('Artysta','Maria', 'Zając', 'Aleja Kasztanowa', '8', '3B', '30-100', 'Kraków', 'Maria Zając to artystka grafik, która specjalizuje się w ilustracjach dla dzieci.'),
('Artysta','Tomasz', 'Kwiatkowski', 'ul. Miejska', '12', NULL, '15-300', 'Białystok', 'Tomasz Kwiatkowski to artysta multimedialny, który często łączy różne media w swoich pracach.'),
('Artysta','Katarzyna', 'Pawlak', 'ul. Bojowa', '6', '4D', '80-200', 'Gdańsk', 'Katarzyna Pawlak to artystka wizualna, której prace często wywołują refleksje na temat czasu i przestrzeni.');
