INSERT INTO Tagi (Wartosc) VALUES
('Pejzaż'),
('Portret'),
('Abstrakcja'),
('Surrealizm'),
('Krajobraz miejski'),
('Natura martwa'),
('Malarstwo historyczne'),
('Impresjonizm'),
('Ekspresjonizm'),
('Kubizm'),
('Nowoczesność'),
('Realizm'),
('Miniatury'),
('Sztuka uliczna'),
('Sztuka fantastyczna'),
('Sztuka cyfrowa'),
('Sztuka konceptualna'),
('Krajobraz wiejski'),
('Malarstwo marynistyczne'),
('Sztuka abstrakcyjna'),
('Sztuka nowoczesna'),
('Sztuka postimpresjonistyczna'),
('Sztuka romantyczna'),
('Sztuka gotycka'),
('Sztuka barokowa'),
('Sztuka renesansowa'),
('Sztuka współczesna'),
('Sztuka minimalna'),
('Sztuka postmodernistyczna'),
('Sztuka performance'),
('Sztuka wideo'),
('Fotorealizm'),
('Malarstwo hiperrealistyczne'),
('Ilustracje'),
('Komiksy'),
('Sztuka klasyczna'),
('Sztuka orientalna'),
('Sztuka etniczna'),
('Sztuka ludowa'),
('Sztuka marynistyczna'),
('Sztuka science fiction'),
('Sztuka fantasy'),
('Sztuka horroru'),
('Sztuka kryminału'),
('Sztuka romantyczna'),
('Sztuka ekspresyjna'),
('Sztuka postkolonialna'),
('Sztuka klasycystyczna'),
('Sztuka futurystyczna'),
('Sztuka awangardowa'),
('Sztuka surrealistyczna'),
('Sztuka dadaistyczna'),
('Sztuka pop-art'),
('Sztuka op-art'),
('Sztuka minimalizmu'),
('Sztuka konceptualna'),
('Sztuka feministyczna'),
('Sztuka ekologiczna'),
('Sztuka społeczna'),
('Sztuka afroamerykańska'),
('Sztuka queer'),
('Sztuka postkolonialna'),
('Sztuka latynoamerykańska'),
('Sztuka azjatycka'),
('Sztuka europejska'),
('Sztuka islamska'),
('Sztuka wschodnioazjatycka'),
('Sztuka aborygeńska'),
('Sztuka chińska'),
('Sztuka japońska'),
('Sztuka indyjska'),
('Sztuka afrykańska'),
('Sztuka maski'),
('Klasyczna harmonia'),
('Minimalizm i prostota'),
('Ekspresjonistyczny chaos'),
('Abstrakcyjna forma'),
('Symetria i równowaga'),
('Kolorowa eksplozja'),
('Pejzażowa harmonia'),
('Subtelne odcienie'),
('Złota proporcja'),
('Współczesna eksperymentacja'),
('Sztuka konceptualna'),
('Bogactwo detali'),
('Sztuka postmodernistyczna'),
('Zimne odcienie niebieskiego'),
('Światło i cień'),
('Dynamika i ruch'),
('Różnorodność faktur'),
('Wzorzyste geometryczne formy'),
('Różnorodność technik'),
('Sztuka ludowa i folklor'),
('Ekspresja koloru'),
('Sztuka abstrakcyjna'),
('Liryczny pejzaż'),
('Nowoczesny ekspresjonizm'),
('Eksperyment w kolorach'),
('Symetria i asymetria'),
('Pełne ekspresji'),
('Sztuka cyfrowa'),
('Różnorodność mediów'),
('Płynność i ruch'),
('Mieszane techniki'),
('Sztuka dynamiczna'),
('Detal w centrum uwagi'),
('Klasyczne linie i proporcje'),
('Nowoczesny minimalizm'),
('Harmonia kolorów'),
('Sztuka konceptualna'),
('Kreatywność i innowacja'),
('Pejzaż romantyczny'),
('Sztuka realistyczna'),
('Wzory i ornamenty'),
('Malarstwo pastelowe'),
('Rzeźba monumentalna'),
('Eksperyment w formach'),
('Sztuka interaktywna'),
('Klasyczne motywy'),
('Sztuka ekspresjonistyczna'),
('Sztuka konkretna');
